---
version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  ui:
    build: web/frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
    environment:
      - REACT_APP_APP_SERVER=http://localhost:5000